FROM python:3.11.9-slim

ENV TZ=Europe/Lisbon
RUN apt-get update && apt-get install -y tzdata && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY script.py .

RUN pip install --no-cache-dir pymongo CoolProp pymodbus

CMD ["python", "script.py"]
